language: objective-c
xcode_project: Xcode-iOS/Test/TestiPhoneOS.xcodeproj
osx_image: xcode9.4
cache:
  directories:
    - XCode-iOS/SDL/Carthage
#
# Edit Cartfile and Cartfile.resolved (those file might be empty if there isn't any dependency)
# Configure all ObjectiveC variables (TRAVIS_*).
# Add platform specific arguments as env: VAR1=value VAR2=value
#
env:
  global:
    - CARTHAGE_PROJECT_DIR=XCode-iOS/SDL
    - CONFIGURATION=Release
matrix:
  include:
  - xcode_scheme: Test-iOS
    xcode_sdk: iphonesimulator11.4
    env: PLATFORM=iOS FRAMEWORK_NAME=SDL2 DESTINATION="platform=iOS Simulator,OS=11.4,name=iPhone
      X" XC_ACTION=test
  - xcode_scheme: Test-tvOS
    xcode_sdk: appletvsimulator11.4
    env: PLATFORM=tvOS FRAMEWORK_NAME=SDL2 DESTINATION="platform=tvOS Simulator,OS=11.4,name=Apple
      TV" XC_ACTION=build
before_install:
# Formatting travis log output
- gem install xcpretty -N
- gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
# Carthage installer
- brew update
- brew outdated carthage || brew upgrade carthage
before_script:
# Comment out this bootstrap if there isn't any dependency
# - carthage bootstrap --project-directory $CARTHAGE_PROJECT_DIR
before_deploy:
# Set up git user name and tag this commit
# requires travis repository settings variables (GIT_*)
- git config --local user.name "$GIT_USER"
- git config --local user.email "$GIT_EMAIL"
- git tag --force "v${GIT_RELEASE_VERSION}.${TRAVIS_BUILD_NUMBER}"
- cd $CARTHAGE_PROJECT_DIR
- carthage build --configuration $CONFIGURATION --cache-builds --no-skip-current #--platform $PLATFORM
- carthage archive $FRAMEWORK_NAME
script:
# Replaces the default built-in xcodebuild command with specified parameters
- xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -destination
  "$DESTINATION" -sdk "$TRAVIS_XCODE_SDK" -configuration $CONFIGURATION CODE_SIGNING_REQUIRED=NO
  $XC_ACTION | xcpretty -f `xcpretty-travis-formatter`
#
# Deployment generated with local CLI travis setup releases --force, with secured github token.
# Enter ${FRAMEWORK_NAME}.framework.zip as the file to upload when prompted.
#
deploy:
  provider: releases
  api_key:
    secure: eFiBrHIQ6tJn28L/Ynu0OH7DReBl6c0mxNoX+iDrIGx0Zhgo8a6AUUGWIxjPZn9g3LCMKE3OadVcOh6ns32lFt5eMXGmUXixXNefKP5ibkW6xDoKAW4XNxr1MUVPr2SXdFQPdGEHDadQuDl7yK6JyKzgwSW/+3ifra7BUcWImln/P5QnsyZk1mBIWMlUa2ibi0dEprosvzyvnA0h86pCTxziXAZYlEnbR+pHSHaty+1cVIiMgAaaBrOfAzCDgtNlHiVKcRYhTebbC/vOF7duNp24CNj6epQEc3O5vBSnGEC1+AKWvSAodQDJtvfX8ZruoK/PtV05C8bVrq/PsHQ/UyCEVnO8C7s0yL9xCR2XpROd6qIVizXYrwi8gvjpw0oLfG0N99vPu7zYEmja5mADr8x4e1i6SeteOSQCS/n/wYKtZHA5nAkuS3Z6Tk4Xt0ac3LtnZF9q3lPtPDKYAABoyqOcpb9fj2JvRCGqNm3IMg/uqR/mS9lczmty4VE972tpwDq5mC5Dt4Sjuk1Y/Hkb5Tt0a/W83JQPAIsU6Fh/SdguF5Vv7Ml5ToaNaoHjEi4u2qFe+oLwl+Ltu3eXda0M7XTyP13tmew5q/mqEitRA8nMeeyOrbknm3FFv/bW7rcXnJ+HLfo6xnTkTKgM7V8oPYR7T1qomaAA/xilzwtTg88=
  file: "${FRAMEWORK_NAME}.framework.zip"
  skip_cleanup: true
  on:
    repo: b23prodtm/SDL2
    branch: feature/*
