language: objective-c
xcode_project: Xcode-iOS/Test/TestiPhoneOS.xcodeproj
osx_image: xcode9.4
env:
  global:
    - CARTHAGE_PROJECT_DIR=XCode-iOS/SDL
    - CONFIGURATION=Release
matrix:
  include:
  - xcode_scheme: Test-iOS
    xcode_sdk: iphonesimulator11.4
    env: FRAMEWORK_NAME=SDL2 DESTINATION="platform=iOS Simulator,OS=11.4,name=iPhone X"
  - xcode_scheme: Test-tvOS
    xcode_sdk: appletvsimulator11.4
    env: FRAMEWORK_NAME=SDL2.tvOS DESTINATION="platform=tvOS Simulator,OS=11.4,name=Apple TV"
before_install:
  - gem install xcpretty -N
  - gem install xcpretty-travis-formatter --no-rdoc --no-ri --no-document --quiet
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  - carthage bootstrap --project-directory $CARTHAGE_PROJECT_DIR
before_deploy:
  - cd $CARTHAGE_PROJECT_DIR
  - carthage build --configuration $CONFIGURATION --cache-builds --no-skip-current
  - carthage archive $FRAMEWORK_NAME
script:
  - xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -destination "$DESTINATION" -sdk "$TRAVIS_XCODE_SDK" -configuration $CONFIGURATION CODE_SIGNING_REQUIRED=NO test | xcpretty -f `xcpretty-travis-formatter`
deploy:
  provider: releases
  api_key:
    secure: Qv+Mn+dkr7wmJILsTrSD5yU60ZLl/q1P2sTRRyHCbpTdNNGbxSKyt/Of9UrExE7gJvQ2sX62jtbsg5vRhkbVnWENn/qc6C62XDmAWkDC4l4F1oWhU23GVahbkO7+N23UdldRWLRz93sselZc66zSq0be9p9GNUeZY0D68AFOu7DeOA26XrKeiH/5K0fERE4WNVCUSdWJBKESBrelgg0+vbboFryLD+OeP5X/4We6HbrX4EIj2dNP/rv0H3yRYNduc5Vjhi0jtGgUrxm4iRi1rdSO67eu2+IO4s9jto4DFRW/jZEnJK3w95pc4f7v2jXeEr+wcl4a6Xjdxpo9W7Gtn7XChNHmlIIhKRTatvPXlaXhGiQBhlCT0qvxVSgJA8YNpKUJX+Qeye32jXLXuM8EowuvRUdEreS3jgUWG+pAtX10HDEocVJlS/WVDBHdlG++cqWvPcjCZe4mc9rgOtEcO0N7aq9zT8daTEqhRNDYB+qFHIgTmfqJ+8zGqJPwImwdthRtURd4NlWxdaKGfAXnE7HNp4nWJ1QNfYzDb1zdu5FfijjwQkFDLnIbYV/43bDnX8cKPykYH+tJzpP0NZuSsoE1a+4KWxcmlQYGIb2FBJ8YmraChHxr7AS3uRj3U+XeGo3U2yn4WrYM1qtZsI/MHnd99BORbV+p9h6WN7Gn8KE=
  file: "$FRAMEWORK_NAME.framework.zip"
  skip_cleanup: true
  on:
    repo: b23prodtm/SDL2
    branch: ios-build
    tags: true
