language: objective-c
xcode_project: Xcode-iOS/Test/TestiPhoneOS.xcodeproj
osx_image: xcode9.4
env:
  global:
    - CARTHAGE_PROJECT_DIR=XCode-iOS/SDL
matrix:
  include:
    - xcode_scheme: Test-iOS
      xcode_sdk: iphonesimulator11.4
      env: FRAMEWORK_NAME=SDL2 DESTINATION="platform=iOS Simulator,OS=11.4,name=iPhone X"
    - xcode_scheme: Test-tvOS
      xcode_sdk: appletvsimulator11.4
      env: FRAMEWORK_NAME=SDL2.tvOS DESTINATION="platform=tvOS Simulator,OS=11.4,name=Apple TV"
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
before_script:
  # bootstrap the dependencies for the project
  # you can remove if you don't have dependencies
  - carthage bootstrap --project-directory $CARTHAGE_PROJECT_DIR
before_deploy:
  - cd $CARTHAGE_PROJECT_DIR
  - carthage build --configuration Release --cache-builds --no-skip-current
  - carthage archive $FRAMEWORK_NAME
script:
  - xcodebuild -project $TRAVIS_XCODE_PROJECT -scheme $TRAVIS_XCODE_SCHEME -destination "$DESTINATION" -sdk "$TRAVIS_XCODE_SDK" CODE_SIGNING_REQUIRED=NO
